# Generated by Django 2.1.4 on 2019-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-picture'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
