# Generated by Django 2.1.4 on 2019-01-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190106_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_picture', models.ImageField(blank=True, null=True, upload_to='profile-picture/extra-picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_picture',
        ),
        migrations.AddField(
            model_name='extraproductpicture',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
