# Generated by Django 2.1.4 on 2019-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190106_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraproductpicture',
            name='extra_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-picture'),
        ),
    ]
